// <auto-generated />
namespace Cblog.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AspnetMembership : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AspnetMembership));
        
        string IMigrationMetadata.Id
        {
            get { return "201208191420060_AspnetMembership"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
