// <auto-generated />
namespace Cblog.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Posts_UrlTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Posts_UrlTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201208201538051_Posts_UrlTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
